worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # === RATE LIMIT ZONES ===
    # umum (browsing)
    limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;
    # endpoint sensitif (login/admin)
    limit_req_zone $binary_remote_addr zone=auth:10m rate=3r/s;

    # koneksi paralel per IP
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    # === BASIC TUNING ===
    sendfile on;
    keepalive_timeout 65;
    types_hash_max_size 10240;

    # === GZIP ===
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;

    # include server blocks
    include /etc/nginx/conf.d/*.conf;
}